version: 1.0.{build}
image: Visual Studio 2017
platform: x64
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: cl /EHsc /W4  test.cpp app.cpp
